controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

my-bundle:
    resource: '@MyBundle/Resources/config/routes.yaml'
    #path: /my
    #controller: my_bundle.controller.my_controller::index